let nombre = "Juan Esteban";
let apellidos = "Rendón Pechené";
let estudiante = nombre.concat(" ", apellidos);
let estudianteMayus = estudiante.toUpperCase();
let estudianteMinus = estudiante.toLowerCase();
let numeroLetras = estudiante.length;
let primeraLetra = nombre.charAt(0);
let ultimaLetra = apellidos.charAt(apellidos.length - 1);
let eliminaEspacios = estudiante.replace(/ /g, "");
let contiene = estudiante.includes(nombre);
console.log(eliminaEspacios);
